#!/bin/bash

# apt -y install unzip

echo -e "\033[31m =============================================================\033[0m"
echo -e "\033[33m                 脚本名：  3trace.sh \033[0m"
echo -e "\033[33m *原作者：@ztang；Github：https://github.com/zq/shell \033[0m"
echo -e "\033[34m *此脚本仅仅丰富了测试用ip地址 \033[0m"
echo -e "\033[34m *运行后自动测试服务器回程到上海北京广州三地电信联通移动路由情况 \033[0m"
echo -e "\033[1;36m *此脚本发布在 http://vpsoff.com \033[0m"
echo -e "\033[31m =============================================================\033[0m"


# install besttrace
if [ ! -f "besttrace" ]; then
    wget https://github.com/zq/shell/raw/master/besttrace
    # unzip besttrace4linux.zip
    chmod +x besttrace
fi

## start to use besttrace

next() {
    printf "%-70s\n" "-" | sed 's/\s/-/g'
}

#clear
next

ip_list=(101.95.120.109 210.22.70.3 183.192.160.3 219.141.136.10 123.125.81.6 221.130.33.52 202.96.128.166 210.21.196.6 211.136.20.203 202.112.14.151)
ip_addr=(上海电信 上海联通 上海移动 北京电信 北京联通 北京移动 广州电信 广州联通 广州移动 成都教育网)
# ip_len=${#ip_list[@]}

for i in {0..9}
do
    echo ${ip_addr[$i]}
    ./besttrace -q 1 ${ip_list[$i]}
    next
done
